import type { HorrorEventDef } from './horrorDirector';

/**
 * HS FLOOR 1 の恐怖イベント定義。
 *
 * ここはデータだけ。「どう鳴らすか」は Floor1Mode 側が id を見て実行する。
 * if文の塊にしないため、条件は全部このテーブルに書く。
 */
export const FLOOR1_HORROR: HorrorEventDef[] = [
  // ---------------- 弱い ----------------
  {
    id: 'LightFlicker',
    family: 'LIGHT',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 52,
    minHaunted: 8,
    preferredTension: [8, 45],
    cooldown: 42,
    familyCooldown: 18,
    repeatPenalty: 20,
    tags: ['ambient'],
    maxPerRun: 5,
  },
  {
    id: 'DistantFootstep',
    family: 'AUDIO',
    intensity: 'minor',
    threat: 'low',
    baseWeight: 50,
    minHaunted: 15,
    preferredTension: [12, 55],
    cooldown: 40,
    familyCooldown: 14,
    maxPerRun: 4,
    tags: ['ambient'],
  },
  {
    id: 'DoorCreak',
    family: 'AUDIO',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 46,
    minHaunted: 10,
    preferredTension: [8, 50],
    cooldown: 44,
    familyCooldown: 14,
    maxPerRun: 3,
  },
  {
    id: 'HouseSettle',
    family: 'AUDIO',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 44,
    preferredTension: [0, 35],
    cooldown: 48,
    familyCooldown: 12,
    maxPerRun: 4,
  },

  // ---------------- 背後 ----------------
  {
    id: 'BehindFootstep',
    family: 'AUDIO',
    intensity: 'medium',
    threat: 'low',
    baseWeight: 52,
    minHaunted: 22,
    preferredTension: [20, 62],
    cooldown: 40,
    familyCooldown: 16,
    maxPerRun: 4,
    tags: ['behind'],
  },

  // ---------------- オブジェクト ----------------
  {
    id: 'PortraitTilt',
    family: 'PORTRAIT',
    intensity: 'minor',
    threat: 'safe',
    baseWeight: 46,
    relatedObject: 'portraits',
    minHaunted: 18,
    preferredTension: [10, 50],
    forbiddenObjectState: 'portraits|wrong',
    cooldown: 70,
    oncePerRun: true,
    minPlayerDistance: 8,
  },
  {
    id: 'MirrorAnomaly',
    family: 'MIRROR',
    intensity: 'medium',
    threat: 'low',
    baseWeight: 44,
    relatedObject: 'mirror',
    minHaunted: 25,
    preferredTension: [18, 60],
    maxPlayerDistance: 9,
    cooldown: 55,
    maxPerRun: 3,
  },
  {
    id: 'FridgeHum',
    family: 'OBJECT',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 40,
    relatedObject: 'fridge',
    requiredObjectState: 'fridge|bugs',
    preferredTension: [5, 45],
    maxPlayerDistance: 16,
    cooldown: 45,
    maxPerRun: 3,
  },

  // ---------------- World Memory に紐づくもの ----------------
  {
    id: 'DistantBell',
    family: 'AUDIO',
    intensity: 'minor',
    threat: 'safe',
    baseWeight: 30,
    relatedObject: 'altar',
    requiredMemories: ['altar_overplayed'],
    preferredTension: [8, 58],
    cooldown: 50,
    maxPerRun: 4,
    anticipationDelay: [1.5, 4],
    tags: ['memory'],
  },
  {
    id: 'DistantPhone',
    family: 'PHONE',
    intensity: 'medium',
    threat: 'safe',
    baseWeight: 30,
    relatedObject: 'phone',
    requiredMemories: ['phone_listened_long'],
    preferredTension: [15, 60],
    cooldown: 60,
    maxPerRun: 3,
    anticipationDelay: [2, 5],
    tags: ['memory', 'phone'],
  },
  {
    id: 'OwnVoice',
    family: 'PHONE',
    intensity: 'strong',
    threat: 'low',
    baseWeight: 26,
    requiredMemories: ['phone_listened_long'],
    minHaunted: 35,
    preferredTension: [25, 62],
    cooldown: 999,
    oncePerRun: true,
    anticipationDelay: [2, 5],
    tags: ['memory', 'phone'],
  },
  {
    id: 'WaterRunning',
    family: 'AUDIO',
    intensity: 'minor',
    threat: 'safe',
    baseWeight: 30,
    relatedObject: 'bath',
    requiredMemories: ['bath_sip_2'],
    preferredTension: [10, 58],
    cooldown: 55,
    maxPerRun: 3,
    anticipationDelay: [1.5, 4.5],
    tags: ['memory'],
  },
  {
    id: 'PortraitChanged',
    family: 'PORTRAIT',
    intensity: 'medium',
    threat: 'low',
    baseWeight: 28,
    relatedObject: 'portraits',
    requiredMemories: ['portrait_restored'],
    preferredTension: [12, 58],
    cooldown: 999,
    oncePerRun: true,
    minPlayerDistance: 6,
    tags: ['memory'],
  },
  {
    id: 'SofaEmpty',
    family: 'GHOST_SPATIAL',
    intensity: 'medium',
    threat: 'medium',
    baseWeight: 30,
    relatedObject: 'ghost',
    requiredMemories: ['ghost_selfie_taken'],
    requiresGhostOffscreen: true,
    preferredTension: [15, 60],
    cooldown: 999,
    oncePerRun: true,
    tags: ['memory', 'ghost'],
  },
  {
    id: 'KitchenNoise',
    family: 'OBJECT',
    intensity: 'minor',
    threat: 'safe',
    baseWeight: 28,
    relatedObject: 'fridge',
    requiredMemories: ['fridge_held_long'],
    preferredTension: [8, 55],
    cooldown: 60,
    maxPerRun: 2,
    anticipationDelay: [1.5, 4],
    tags: ['memory'],
  },

  // ---------------- 幽霊 ----------------
  {
    id: 'GhostPeek',
    family: 'GHOST_VISUAL',
    intensity: 'medium',
    threat: 'medium',
    baseWeight: 48,
    minHaunted: 28,
    preferredTension: [20, 58],
    requiredGhostState: ['aware', 'standing', 'stalking'],
    requiresGhostOffscreen: true,
    cooldown: 45,
    familyCooldown: 20,
    maxPerRun: 4,
    tags: ['ghost'],
  },
  {
    id: 'GhostReposition',
    family: 'GHOST_SPATIAL',
    intensity: 'medium',
    threat: 'medium',
    baseWeight: 46,
    minHaunted: 40,
    preferredTension: [25, 65],
    requiredGhostState: ['aware', 'standing', 'stalking'],
    requiresGhostOffscreen: true,
    cooldown: 40,
    familyCooldown: 18,
    maxPerRun: 5,
    tags: ['behind', 'ghost'],
  },
  {
    id: 'GhostCrossing',
    family: 'GHOST_VISUAL',
    intensity: 'medium',
    threat: 'medium',
    baseWeight: 44,
    minHaunted: 35,
    preferredTension: [22, 60],
    requiredGhostState: ['standing', 'stalking'],
    requiresGhostOffscreen: true,
    cooldown: 50,
    maxPerRun: 3,
    tags: ['ghost'],
  },
  {
    id: 'GhostStand',
    family: 'GHOST_VISUAL',
    intensity: 'strong',
    threat: 'high',
    baseWeight: 44,
    minHaunted: 30,
    preferredTension: [20, 55],
    requiredGhostState: ['aware'],
    cooldown: 999,
    oncePerRun: true,
    tags: ['ghost'],
  },
  {
    id: 'FakeRush',
    family: 'FAKE_THREAT',
    intensity: 'strong',
    threat: 'high',
    baseWeight: 40,
    minHaunted: 60,
    preferredTension: [35, 68],
    requiredGhostState: ['standing', 'stalking'],
    maxPlayerDistance: 16,
    cooldown: 70,
    maxPerRun: 2,
    tags: ['ghost'],
  },

  // ---------------- 低 Haunted 用の「気のせいかもしれない」語彙 ----------------
  // 明確な超常現象を増やすのではなく、確信の持てない違和感の語彙を増やす（§13-15）。
  // どれも subtle / 弱い minor。Tension もほとんど動かさない。
  {
    id: 'HousePop',
    family: 'AMBIENT_HOUSE',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 34,
    preferredTension: [0, 40],
    cooldown: 50,
    familyCooldown: 20,
    maxPerRun: 4,
    sources: ['ahead', 'side', 'distant_room'],
    variants: 3,
    tags: ['ambient'],
  },
  {
    id: 'FloorCreakDistant',
    family: 'AMBIENT_HOUSE',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 33,
    preferredTension: [0, 44],
    cooldown: 52,
    familyCooldown: 20,
    maxPerRun: 4,
    sources: ['distant_room', 'behind', 'side'],
    variants: 3,
    tags: ['ambient'],
  },
  {
    id: 'PipeKnock',
    family: 'AMBIENT_WATER',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 32,
    preferredTension: [0, 46],
    cooldown: 55,
    familyCooldown: 22,
    maxPerRun: 3,
    sources: ['distant_room', 'side'],
    variants: 2,
    tags: ['ambient'],
  },
  {
    id: 'DistantWaterDrop',
    family: 'AMBIENT_WATER',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 31,
    preferredTension: [0, 46],
    cooldown: 50,
    familyCooldown: 22,
    maxPerRun: 4,
    sources: ['distant_room', 'ahead'],
    variants: 3,
    tags: ['ambient'],
  },
  {
    id: 'FridgeHumStop',
    family: 'AMBIENT_ELECTRIC',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 32,
    relatedObject: 'fridge',
    preferredTension: [0, 44],
    maxPlayerDistance: 22,
    cooldown: 60,
    familyCooldown: 22,
    maxPerRun: 2,
    sources: ['same_room', 'distant_room'],
    tags: ['ambient'],
  },
  {
    id: 'TVStaticTick',
    family: 'AMBIENT_ELECTRIC',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 30,
    relatedObject: 'tv',
    preferredTension: [0, 46],
    maxPlayerDistance: 20,
    cooldown: 55,
    familyCooldown: 22,
    maxPerRun: 3,
    sources: ['same_room', 'ahead'],
    variants: 2,
    tags: ['ambient'],
  },
  {
    id: 'PhoneClick',
    family: 'AMBIENT_ELECTRIC',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 30,
    relatedObject: 'phone',
    preferredTension: [0, 48],
    cooldown: 58,
    familyCooldown: 22,
    maxPerRun: 3,
    sources: ['distant_room', 'side'],
    variants: 2,
    tags: ['ambient', 'phone'],
  },
  {
    id: 'LightCordSway',
    family: 'AMBIENT_OBJECT',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 32,
    relatedObject: 'altar',
    preferredTension: [0, 46],
    maxPlayerDistance: 14,
    cooldown: 58,
    familyCooldown: 20,
    maxPerRun: 3,
    sources: ['ahead', 'side'],
    tags: ['ambient'],
  },
  {
    id: 'ObjectTinyShift',
    family: 'AMBIENT_OBJECT',
    intensity: 'minor',
    threat: 'safe',
    baseWeight: 30,
    minHaunted: 12,
    preferredTension: [4, 50],
    cooldown: 62,
    familyCooldown: 20,
    maxPerRun: 3,
    sources: ['behind', 'side'],
    variants: 2,
    tags: ['ambient', 'behind'],
  },
  {
    id: 'FabricRustle',
    family: 'AMBIENT_LIVING',
    intensity: 'subtle',
    threat: 'safe',
    baseWeight: 30,
    relatedObject: 'sofa',
    preferredTension: [0, 48],
    cooldown: 56,
    familyCooldown: 20,
    maxPerRun: 3,
    sources: ['distant_room', 'behind', 'side'],
    variants: 2,
    tags: ['ambient'],
  },

  // ---------------- Safe Suspense Peak ----------------
  // 「強い演出」だが「実際には安全」な山。
  // 安全に遊ぶプレイヤーの Run が、家鳴りだけで終わらないようにするためのもの。
  // ここから Chase へ繋げてはいけない（§11）。危険は自分で買うもの。
  {
    id: 'PortraitCrash',
    family: 'PORTRAIT',
    intensity: 'strong',
    threat: 'safe',
    baseWeight: 40,
    relatedObject: 'portraits',
    forbiddenObjectState: 'portraits|wrong',
    minHaunted: 10,
    preferredTension: [10, 62],
    // 見ている時に落ちるのが本命。音だけ聞こえる版は下の PortraitFellUnseen（§55-58）
    preferOnScreen: true,
    anticipationDelay: [0.3, 1.5],
    cooldown: 999,
    oncePerRun: true,
    tags: ['peak'],
  },
  {
    // 「音だけ聞こえて、戻ったら落ちている」版。重みは低く保つ
    id: 'PortraitFellUnseen',
    family: 'PORTRAIT',
    intensity: 'medium',
    threat: 'safe',
    baseWeight: 18,
    relatedObject: 'portraits',
    forbiddenObjectState: 'portraits|wrong',
    minHaunted: 14,
    preferredTension: [8, 58],
    minPlayerDistance: 10,
    cooldown: 999,
    oncePerRun: true,
    tags: ['ambient'],
  },
  {
    id: 'PhoneSuddenRing',
    family: 'PHONE',
    intensity: 'strong',
    threat: 'safe',
    baseWeight: 32,
    relatedObject: 'phone',
    minHaunted: 10,
    preferredTension: [10, 62],
    cooldown: 999,
    oncePerRun: true,
    tags: ['peak', 'phone'],
  },
  {
    id: 'WholeHouseLightDrop',
    family: 'LIGHT',
    intensity: 'strong',
    threat: 'safe',
    baseWeight: 38,
    minHaunted: 12,
    preferredTension: [10, 66],
    cooldown: 999,
    oncePerRun: true,
    tags: ['peak'],
  },
  {
    id: 'TVSuddenOn',
    family: 'OBJECT',
    intensity: 'strong',
    threat: 'safe',
    baseWeight: 36,
    relatedObject: 'tv',
    minHaunted: 14,
    preferredTension: [10, 64],
    maxPlayerDistance: 24,
    cooldown: 999,
    oncePerRun: true,
    tags: ['peak'],
  },
  {
    id: 'BathroomDoorMove',
    family: 'OBJECT',
    intensity: 'strong',
    threat: 'safe',
    baseWeight: 36,
    relatedObject: 'bath',
    minHaunted: 12,
    preferredTension: [10, 64],
    maxPlayerDistance: 22,
    cooldown: 999,
    oncePerRun: true,
    tags: ['peak'],
  },
  {
    id: 'HallwaySilhouetteCross',
    family: 'GHOST_VISUAL',
    intensity: 'strong',
    threat: 'low',
    baseWeight: 38,
    minHaunted: 16,
    preferredTension: [12, 66],
    requiresGhostOffscreen: true,
    cooldown: 999,
    oncePerRun: true,
    tags: ['peak', 'ghost'],
  },
  {
    id: 'SofaPostureChange',
    family: 'GHOST_VISUAL',
    intensity: 'strong',
    threat: 'low',
    baseWeight: 36,
    relatedObject: 'ghost',
    minHaunted: 14,
    preferredTension: [10, 62],
    requiredGhostState: ['seated', 'aware'],
    requiresGhostOffscreen: true,
    minPlayerDistance: 7,
    cooldown: 999,
    oncePerRun: true,
    tags: ['peak', 'ghost'],
  },
];
