import type { HorrorEventDef } from './horrorDirector';

/**
 * HS FLOOR 1 の恐怖イベント定義。
 *
 * ここはデータだけ。「どう鳴らすか」は Floor1Mode 側が id を見て実行する。
 * if文の塊にしないため、条件は全部このテーブルに書く。
 */
export const FLOOR1_HORROR: HorrorEventDef[] = [
  // ---------------- 弱い ----------------
  {
    id: 'LightFlicker',
    family: 'LIGHT',
    intensity: 'subtle',
    baseWeight: 52,
    minHaunted: 8,
    preferredTension: [8, 45],
    cooldown: 42,
    familyCooldown: 18,
    repeatPenalty: 20,
    tags: ['ambient'],
    maxPerRun: 5,
  },
  {
    id: 'DistantFootstep',
    family: 'AUDIO',
    intensity: 'minor',
    baseWeight: 50,
    minHaunted: 15,
    preferredTension: [12, 55],
    cooldown: 40,
    familyCooldown: 14,
    maxPerRun: 4,
    tags: ['ambient'],
  },
  {
    id: 'DoorCreak',
    family: 'AUDIO',
    intensity: 'subtle',
    baseWeight: 46,
    minHaunted: 10,
    preferredTension: [8, 50],
    cooldown: 44,
    familyCooldown: 14,
    maxPerRun: 3,
  },
  {
    id: 'HouseSettle',
    family: 'AUDIO',
    intensity: 'subtle',
    baseWeight: 44,
    preferredTension: [0, 35],
    cooldown: 48,
    familyCooldown: 12,
    maxPerRun: 4,
  },

  // ---------------- 背後 ----------------
  {
    id: 'BehindFootstep',
    family: 'AUDIO',
    intensity: 'medium',
    baseWeight: 48,
    minHaunted: 22,
    preferredTension: [20, 62],
    cooldown: 40,
    familyCooldown: 16,
    maxPerRun: 4,
    tags: ['behind'],
  },

  // ---------------- オブジェクト ----------------
  {
    id: 'PortraitTilt',
    family: 'PORTRAIT',
    intensity: 'minor',
    baseWeight: 46,
    relatedObject: 'portraits',
    minHaunted: 18,
    preferredTension: [10, 50],
    forbiddenObjectState: 'portraits|wrong',
    cooldown: 70,
    oncePerRun: true,
    minPlayerDistance: 8,
  },
  {
    id: 'MirrorAnomaly',
    family: 'MIRROR',
    intensity: 'medium',
    baseWeight: 44,
    relatedObject: 'mirror',
    minHaunted: 25,
    preferredTension: [18, 60],
    maxPlayerDistance: 9,
    cooldown: 55,
    maxPerRun: 3,
  },
  {
    id: 'FridgeHum',
    family: 'OBJECT',
    intensity: 'subtle',
    baseWeight: 40,
    relatedObject: 'fridge',
    requiredObjectState: 'fridge|bugs',
    preferredTension: [5, 45],
    maxPlayerDistance: 16,
    cooldown: 45,
    maxPerRun: 3,
  },

  // ---------------- World Memory に紐づくもの ----------------
  {
    id: 'DistantBell',
    family: 'AUDIO',
    intensity: 'minor',
    baseWeight: 30,
    relatedObject: 'altar',
    requiredMemories: ['altar_overplayed'],
    preferredTension: [8, 58],
    cooldown: 50,
    maxPerRun: 4,
    anticipationDelay: [1.5, 4],
    tags: ['memory'],
  },
  {
    id: 'DistantPhone',
    family: 'PHONE',
    intensity: 'medium',
    baseWeight: 30,
    relatedObject: 'phone',
    requiredMemories: ['phone_listened_long'],
    preferredTension: [15, 60],
    cooldown: 60,
    maxPerRun: 3,
    anticipationDelay: [2, 5],
    tags: ['memory'],
  },
  {
    id: 'OwnVoice',
    family: 'PHONE',
    intensity: 'strong',
    baseWeight: 26,
    requiredMemories: ['phone_listened_long'],
    minHaunted: 35,
    preferredTension: [25, 62],
    cooldown: 999,
    oncePerRun: true,
    anticipationDelay: [2, 5],
    tags: ['memory'],
  },
  {
    id: 'WaterRunning',
    family: 'AUDIO',
    intensity: 'minor',
    baseWeight: 30,
    relatedObject: 'bath',
    requiredMemories: ['bath_sip_2'],
    preferredTension: [10, 58],
    cooldown: 55,
    maxPerRun: 3,
    anticipationDelay: [1.5, 4.5],
    tags: ['memory'],
  },
  {
    id: 'PortraitChanged',
    family: 'PORTRAIT',
    intensity: 'medium',
    baseWeight: 28,
    relatedObject: 'portraits',
    requiredMemories: ['portrait_restored'],
    preferredTension: [12, 58],
    cooldown: 999,
    oncePerRun: true,
    minPlayerDistance: 6,
    tags: ['memory'],
  },
  {
    id: 'SofaEmpty',
    family: 'GHOST_SPATIAL',
    intensity: 'medium',
    baseWeight: 30,
    relatedObject: 'ghost',
    requiredMemories: ['ghost_selfie_taken'],
    requiresGhostOffscreen: true,
    preferredTension: [15, 60],
    cooldown: 999,
    oncePerRun: true,
    tags: ['memory'],
  },
  {
    id: 'KitchenNoise',
    family: 'OBJECT',
    intensity: 'minor',
    baseWeight: 28,
    relatedObject: 'fridge',
    requiredMemories: ['fridge_held_long'],
    preferredTension: [8, 55],
    cooldown: 60,
    maxPerRun: 2,
    anticipationDelay: [1.5, 4],
    tags: ['memory'],
  },

  // ---------------- 幽霊 ----------------
  {
    id: 'GhostPeek',
    family: 'GHOST_VISUAL',
    intensity: 'medium',
    baseWeight: 42,
    minHaunted: 28,
    preferredTension: [20, 58],
    requiredGhostState: ['aware', 'standing', 'stalking'],
    requiresGhostOffscreen: true,
    cooldown: 45,
    familyCooldown: 20,
    maxPerRun: 4,
  },
  {
    id: 'GhostReposition',
    family: 'GHOST_SPATIAL',
    intensity: 'medium',
    baseWeight: 40,
    minHaunted: 40,
    preferredTension: [25, 65],
    requiredGhostState: ['aware', 'standing', 'stalking'],
    requiresGhostOffscreen: true,
    cooldown: 40,
    familyCooldown: 18,
    maxPerRun: 5,
    tags: ['behind'],
  },
  {
    id: 'GhostCrossing',
    family: 'GHOST_VISUAL',
    intensity: 'medium',
    baseWeight: 38,
    minHaunted: 35,
    preferredTension: [22, 60],
    requiredGhostState: ['standing', 'stalking'],
    requiresGhostOffscreen: true,
    cooldown: 50,
    maxPerRun: 3,
  },
  {
    id: 'GhostStand',
    family: 'GHOST_VISUAL',
    intensity: 'strong',
    baseWeight: 34,
    minHaunted: 30,
    preferredTension: [20, 55],
    requiredGhostState: ['aware'],
    cooldown: 999,
    oncePerRun: true,
  },
  {
    id: 'FakeRush',
    family: 'FAKE_THREAT',
    intensity: 'strong',
    baseWeight: 30,
    minHaunted: 60,
    preferredTension: [35, 68],
    requiredGhostState: ['standing', 'stalking'],
    maxPlayerDistance: 16,
    cooldown: 70,
    maxPerRun: 2,
  },
];
